###
POST http://localhost:3000/auth/sign-up
Content-Type : application/json

{
    "email" : "codeit05@codeit.com",
    "password" : "!codeit05",
    "nickname" : "코드잇99"
}

###
POST http://localhost:3000/auth/sign-in
Content-Type : application/json

{
    "email" : "codeit01@codeit.com",
    "password" : "!codeit01"
}

###
POST http://localhost:3000/auth/sign-out
Content-Type : application/json
Cookie: connect.sid=YOUR_SESSION_COOKIE_HERE


###
POST https://one-favoritephoto-1-be.onrender.com/auth/sign-up
Content-Type : application/json

{
    "email" : "150qwe@codeit.com",
    "password" : "!codeit06",
    "nickname" : "코드잇000"
}

###
POST https://one-favoritephoto-1-be.onrender.com/auth/sign-in
Content-Type : application/json

{
    "email" : "150qwe@codeit.com",
    "password" : "!codeit06"
}

###
POST https://one-favoritephoto-1-be.onrender.com/auth/sign-out