###
POST http://localhost:3000/auth/sign-up
Content-Type : application/json

{
    "email" : "codeit05@codeit.com",
    "password" : "!codeit05",
    "nickname" : "코드잇02"
}

###
POST http://localhost:3000/auth/sign-in
Content-Type : application/json

{
    "email" : "codeit05@codeit.com",
    "password" : "!codeit05"
}

###
POST http://localhost:3000/auth/sign-out
Content-Type : application/json
Cookie: connect.sid=YOUR_SESSION_COOKIE_HERE


###
POST https://one-favoritephoto-1-be.onrender.com/auth/sign-up
Content-Type : application/json

{
    "email" : "codeit06@codeit.com",
    "password" : "!codeit06",
    "nickname" : "코드잇06"
}

###
POST https://one-favoritephoto-1-be.onrender.com/auth/sign-in
Content-Type : application/json

{
    "email" : "codeit04@codeit.com",
    "password" : "!codeit04"
}

###
POST https://one-favoritephoto-1-be.onrender.com/auth/sign-out