POST http://localhost:3000/shop/exchange
Content-Type : application/json
Cookie: connect.sid=YOUR_SESSION_COOKIE_HERE

{
    "shopId" : "b49e0270-04b4-4d69-aea8-f720c3cefbe6",
    "cardId" : "0f4939d0-aab9-48b8-a1b0-6958f97908d9",
    "description" :"교환 신청 테스트00"
}

###
POST http://localhost:3000/users/my-cards
Content-Type : application/json
Cookie: connect.sid=YOUR_SESSION_COOKIE_HERE

{
  "name" : "음식",
  "description" : "독서와 미식",
  "image" : "https://cdn.pixabay.com/photo/2017/04/05/01/16/food-2203732_640.jpg",
  "grade" : 3,
  "genre" : 4,
  "price" : 4,
  "quantity" : 2
}

###
GET http://localhost:3000/shop/3860b272-c816-4f52-bf09-1e0227f639ee
Content-Type : application/json
Cookie: connect.sid=YOUR_SESSION_COOKIE_HERE

###
GET http://localhost:3000/shop
Content-Type : application/json
Cookie: connect.sid=YOUR_SESSION_COOKIE_HERE

###
GET http://localhost:3000/users/my-cards/fd3d66c0-b702-40b9-928a-371b68f0fd64
Content-Type : application/json
Cookie: connect.sid=YOUR_SESSION_COOKIE_HERE

###
GET http://localhost:3000/users/shop
Content-Type : application/json
Cookie: connect.sid=YOUR_SESSION_COOKIE_HERE

###
GET http://localhost:3000/users/my-cards
Content-Type : application/json
Cookie: connect.sid=YOUR_SESSION_COOKIE_HERE

###
GET http://localhost:3000/users/exchange
Content-Type : application/json
Cookie: connect.sid=YOUR_SESSION_COOKIE_HERE

###
POST http://localhost:3000/auth/sign-in
Content-Type : application/json

{
    "email" : "codeit05@codeit.com",
    "password" : "!codeit05"
}

###
POST http://localhost:3000/auth/sign-in
Content-Type : application/json

{
    "email" : "codeit01@codeit.com",
    "password" : "!codeit01"
}

###
POST http://localhost:3000/auth/sign-out


###
POST http://localhost:3000/exchange/1596e3d0-7788-4f10-a2ae-f76e5dac860c/accept
Cookie: connect.sid=YOUR_SESSION_COOKIE_HERE

###
POST http://localhost:3000/exchange/8507947e-20cf-4e8d-b48f-f9053f772e5b/refuse
Cookie: connect.sid=YOUR_SESSION_COOKIE_HERE

###
DELETE http://localhost:3000/exchange/cfc86b35-9782-46f6-8064-053e0129d126
Cookie: connect.sid=YOUR_SESSION_COOKIE_HERE


###
POST https://one-favoritephoto-1-be.onrender.com/auth/sign-in
Content-Type : application/json

{
    "email" : "codeit05@codeit.com",
    "password" : "!codeit05"
}


###
GET  https://one-favoritephoto-1-be.onrender.com/users/shop
Content-Type : application/json
Cookie: connect.sid=YOUR_SESSION_COOKIE_HERE

###
GET https://one-favoritephoto-1-be.onrender.com/shop/3860b272-c816-4f52-bf09-1e0227f639ee
Content-Type : application/json
Cookie: connect.sid=YOUR_SESSION_COOKIE_HERE