###
GET http://localhost:3000/notifications
Content-Type : application/json

###
PATCH http://localhost:3000/notifications
Content-Type : application/json

###
delete http://localhost:3000/notifications
Content-Type : application/json

###
POST http://localhost:3000/auth/sign-in
Content-Type : application/json

{
    "email" : "codeit05@codeit.com",
    "password" : "!codeit05"
}

###
POST http://localhost:3000/auth/sign-out
Content-Type : application/json