###
GET http://localhost:3000/users/notifications
Content-Type : application/json

###
PATCH http://localhost:3000/notifications/c6c33d96-9917-4a08-8800-7f3026eeb183
Content-Type : application/json

###
delete http://localhost:3000/notifications/c6c33d96-9917-4a08-8800-7f3026eeb183
Content-Type : application/json

###
POST http://localhost:3000/auth/sign-in
Content-Type : application/json

{
    "email" : "codeit03@codeit.com",
    "password" : "!codeit03"
}

###
POST http://localhost:3000/auth/sign-out
Content-Type : application/json