###
GET http://localhost:3000/points/last-box-time
Content-Type : application/json
Cookie: connect.sid=YOUR_SESSION_COOKIE_HERE


###
POST http://localhost:3000/points/box
Content-Type : application/json
Cookie: connect.sid=YOUR_SESSION_COOKIE_HERE


###
POST http://localhost:3000/auth/sign-in
Content-Type : application/json

{
    "email" : "codeit05@codeit.com",
    "password" : "!codeit05"
}