###
POST http://localhost:3000/shop
Content-Type: application/json
Cookie: connect.sid=YOUR_SESSION_COOKIE_HERE

{
    "cardId": "f1058fd0-b9a0-46d0-afeb-4af59a0bf6f7",
    "salesQuantity": 1,
    "price": 4,
    "exchangeGrade": 1,
    "exchangeGenre": 2,
    "exchangeDescription": "테스트 진행중"
}

###
GET http://localhost:3000/shop?genre=0&&grade=0&&keyword=i&&pageSize=&&pageNum=&&sellout=false

###
GET http://localhost:3000/shop/b49e0270-04b4-4d69-aea8-f720c3cefbe6
Cookie: connect.sid=YOUR_SESSION_COOKIE_HERE

###
PATCH http://localhost:3000/shop/601cb12a-2ab9-49d4-a75e-b64295c3939b
Content-Type: application/json
Cookie: connect.sid=YOUR_SESSION_COOKIE_HERE

{
    "salesQuantity": 1,
    "price": 4,
    "exchangeGrade": 0,
    "exchangeGenre": 4,
    "exchangeDescription": "테스트 진행중"
}

###
POST http://localhost:3000/shop/cbb24524-6818-4b46-8afb-00dd26f379ba/purchase
Content-Type: application/json
Cookie: connect.sid=YOUR_SESSION_COOKIE_HERE

{
    "purchaseQuantity": 1
}

###
GET http://localhost:3000/shop/cbb24524-6818-4b46-8afb-00dd26f379ba/quantity

###
PATCH  https://one-favoritephoto-1-be.onrender.com/shop/8d444419-89d6-46b7-987c-89fc12f231aa
Content-Type: application/json
Cookie: connect.sid=YOUR_SESSION_COOKIE_HERE

{
    "salesQuantity": 1,
    "price": 4,
    "exchangeGrade": 0,
    "exchangeGenre": 4,
    "exchangeDescription": "테스트 진행중"
}