###
GET http://localhost:3000/users/my-cards
Content-Type : application/json
Cookie: connect.sid=YOUR_SESSION_COOKIE_HERE

###
GET http://localhost:3000/users/my-cards?genre=1&&grade=0&&pageSize=15&&pageNum=1
Content-Type : application/json
Cookie: connect.sid=YOUR_SESSION_COOKIE_HERE

###
GET http://localhost:3000/users/my-cards?genre=0&&grade=&&keyword=&&pageSize=15&&pageNum=1
Content-Type : application/json
Cookie: connect.sid=YOUR_SESSION_COOKIE_HERE


###
POST http://localhost:3000/users/my-cards
Content-Type : application/json
Cookie: connect.sid=YOUR_SESSION_COOKIE_HERE

{
  "name" : "낮 펭귄",
  "description" : "동물 펭귄01",
  "image" : "https://cdn.pixabay.com/photo/2024/09/07/02/34/penguins-9028827_640.jpg",
  "grade" : 3,
  "genre" : 2,
  "price" : 4,
  "quantity" : 7
}

###
POST http://localhost:3000/shop
Content-Type: application/json
Cookie: connect.sid=YOUR_SESSION_COOKIE_HERE

{
    "cardId": "c618558f-f82a-456e-bb98-62084afc7954",
    "salesQuantity": 2,
    "price": 4,
    "exchangeGrade": 1,
    "exchangeGenre": 3,
    "exchangeDescription": "테스트 진행중2"
}

###
DELETE http://localhost:3000/shop/20f8df52-5e57-41da-99ff-8487564fd022
Content-Type: application/json
Cookie: connect.sid=YOUR_SESSION_COOKIE_HERE

###
GET http://localhost:3000/users/my-cards/shop
Content-Type : application/json
Cookie: connect.sid=YOUR_SESSION_COOKIE_HERE

###
GET http://localhost:3000/users/my-cards/shop?genre=0&&grade=3&&pageSize=15&&pageNum=1&&sellout=false&&keyword=
Content-Type : application/json
Cookie: connect.sid=YOUR_SESSION_COOKIE_HERE

###
GET http://localhost:3000/users/my-cards/shop?genre=0&&grade=&&keyword=&&pageSize=15&&pageNum=1
Content-Type : application/json
Cookie: connect.sid=YOUR_SESSION_COOKIE_HERE

###
GET http://localhost:3000/users/my-cards/exchange
Content-Type : application/json
Cookie: connect.sid=YOUR_SESSION_COOKIE_HERE

###
GET http://localhost:3000/users/my-cards/exchange?genre=0&&grade=3&&pageSize=15&&pageNum=1&&sellout=false&&keyword=
Content-Type : application/json
Cookie: connect.sid=YOUR_SESSION_COOKIE_HERE

###
GET http://localhost:3000/users/my-cards/exchange?genre=0&&grade=&&keyword=&&pageSize=15&&pageNum=1
Content-Type : application/json
Cookie: connect.sid=YOUR_SESSION_COOKIE_HERE

###
POST http://localhost:3000/auth/sign-in
Content-Type : application/json

{
    "email" : "codeit05@codeit.com",
    "password" : "!codeit05"
}

###
GET https://one-favoritephoto-1-be.onrender.com/users/my-cards
Content-Type : application/json
Cookie: connect.sid=YOUR_SESSION_COOKIE_HERE

###
GET  https://one-favoritephoto-1-be.onrender.com/users/my-cards?genre=1&&grade=0&&pageSize=15&&pageNum=1
Content-Type : application/json
Cookie: connect.sid=YOUR_SESSION_COOKIE_HERE

###
POST https://one-favoritephoto-1-be.onrender.com/users/my-cards
Content-Type : application/json
Cookie: connect.sid=YOUR_SESSION_COOKIE_HERE

{
  "name" : "테스트 이미지6",
  "description" : "카드 생성 테스트6",
  "image" : "https://cdn.pixabay.com/photo/2023/06/14/23/12/sunset-8064078_1280.jpg",
  "grade" : 2,
  "genre" : 2,
  "price" : 3,
  "quantity" : 7
}

###
POST https://one-favoritephoto-1-be.onrender.com/auth/sign-in
Content-Type : application/json

{
  "email" : "codeit05@codeit.com",
  "password" : "!codeit05"
}