###
GET http://localhost:3000/users/my-cards
Content-Type : application/json
Cookie: connect.sid=YOUR_SESSION_COOKIE_HERE


###
POST http://localhost:3000/users/my-cards
Content-Type : application/json
Cookie: connect.sid=YOUR_SESSION_COOKIE_HERE

{
  "name" : "테스트 이미지3",
  "description" : "카드 생성 테스트3",
  "image" : "https://cdn.pixabay.com/photo/2023/06/14/23/12/sunset-8064078_1280.jpg",
  "grade" : 0,
  "genre" : 1,
  "price" : 3,
  "quantity" : 8
}

###
POST http://localhost:3000/auth/sign-in
Content-Type : application/json

{
    "email" : "codeit05@codeit.com",
    "password" : "!codeit05"
}