const NAME_MIN_LENGTH = 1;
const NAME_MAX_LENGTH = 50;
const DESCRIPTION_MIN_LENGTH = 1;
const DESCRIPTION_MAX_LENGTH = 1024;
const IMAGE_MIN_LENGTH = 1;
const IMAGE_MAX_LENGTH = 2048;
const PRICE_MIN_VALUE = 1;
const PRICE_MAX_VALUE = 999;
const GRADE_MIN_VALUE = 0;
const GRADE_MAX_VALUE = 3;
const GENRE_MIN_VALUE = 0;
const GENRE_MAX_VALUE = 5;
const QUANTITY_MIN_VALUE = 1;
const QUANTITY_MAX_VALUE = 99;

export default {
  NAME_MIN_LENGTH,
  NAME_MAX_LENGTH,
  DESCRIPTION_MIN_LENGTH,
  DESCRIPTION_MAX_LENGTH,
  IMAGE_MIN_LENGTH,
  IMAGE_MAX_LENGTH,
  PRICE_MIN_VALUE,
  PRICE_MAX_VALUE,
  GRADE_MIN_VALUE,
  GRADE_MAX_VALUE,
  GENRE_MIN_VALUE,
  GENRE_MAX_VALUE,
  QUANTITY_MIN_VALUE,
  QUANTITY_MAX_VALUE,
};
