export const SUCCESSFUL_EXCHANGE_INDEX = 0;
export const FAILES_EXCHANGE_INDEX = 1;
export const EXCHANGE_PROPOSAL_INDEX = 2;
export const PURCHASE_SUCCESS_INDEX = 3;
export const SALE_NOTIFICATION_INDEX = 4;
export const SOLD_OUT_INDEX = 5;
