const EMAIL_MIN_LENGTH = 1;
const EMAIL_MAX_LENGTH = 254;
const PASSWORD_MIN_LENGTH = 8;
const PASSWORD_MAX_LENGTH = 24;
const NICKNAME_MIN_LENGTH = 1;
const NICKNAME_MAX_LENGTH = 50;

export default {
  EMAIL_MIN_LENGTH,
  EMAIL_MAX_LENGTH,
  PASSWORD_MIN_LENGTH,
  PASSWORD_MAX_LENGTH,
  NICKNAME_MIN_LENGTH,
  NICKNAME_MAX_LENGTH,
};
